name: blockmodel-environment
channels:
  - ostrokach-forge
  - defaults
  - conda-forge
  - pkgw-forge
  - anaconda
dependencies:
  - python
  - gtk3
  - pygobject
  - matplotlib
  - scikit-learn
  - numpy
  - pandas
  - graph-tool
